### PR TITLE
feat: Add Auth Context & MockupServer

### PR DESCRIPTION
**Pull request by bonino97**

### CODE REVIEW

**Review by fuzilogik2019 — APPROVED** [review]

**Review by bonino97 — COMMENTED** [review]
Aprobada

**Comment by bonino97** [comment]
LGTM

**Comment by bonino97** [comment]
LGTB

**Comment by bonino97** [comment]
Massa puto

**Comment by bonino97** [comment]
#MassaNoVasASerPresidente

**Pull request merged**
